######################################################################
# Automatically generated by qmake (3.1) Sun Mar 2 00:12:06 2025
######################################################################

TEMPLATE = app
TARGET = land-cover-classfication
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += graphicdisplay.h \
           mainwindow.h \
           qcombobox_tab.h \
           tool.h \
           build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/include/ui_graphicdisplay.h \
           build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/include/ui_mainwindow.h \
           build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/include/ui_qcombobox_itemwidget.h \
           build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/include/ui_qcombobox_tab.h \
           /build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/include/ui_graphicdisplay.h \
           /build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/include/ui_mainwindow.h \
           D:/my-land-cover-classfication/land-cover-classfication/graphicdisplay.h \
           /build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/include/ui_qcombobox_tab.h \
           build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/EWIEGA46WW/moc_graphicdisplay.cpp \
           build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/EWIEGA46WW/moc_mainwindow.cpp \
           build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/EWIEGA46WW/moc_qcombobox_tab.cpp
FORMS += graphicdisplay.ui mainwindow.ui qcombobox_tab.ui
SOURCES += graphicdisplay.cpp \
           main.cpp \
           mainwindow.cpp \
           qcombobox_tab.cpp \
           tool.cpp \
           build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/mocs_compilation.cpp \
           build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/land-cover-classfication_autogen/EWIEGA46WW/qrc_res.cpp \
           build/Desktop_Qt_6_8_1_llvm_mingw_64_bit-Debug/CMakeFiles/3.29.3/CompilerIdCXX/CMakeCXXCompilerId.cpp \
           D:/my-land-cover-classfication/land-cover-classfication/graphicdisplay.cpp
RESOURCES += res.qrc
TRANSLATIONS += land-cover-classfication_zh_CN.ts
